version: '3.7'
services:

  app:
    build:
      context: ./app
      dockerfile: dockerfile-dev
    depends_on:
      - database
    environment:
      - flask_env=dev
    command: python3 main.py
    ports:
    - 8080:8080

  database:
    image: "mongo:4.2"
    expose:
    - 27017
    

